sapcc/vrops-exporter

tests/TestCollectors.py

InventoryBuilder-Serivce crashes, because it tries to connect to the vROPS server (testhost.test).
The problem is, InventoryBuilder executes the method, before the Mocks are in place

Fix Mock in TestCollectors.py

---

exporter.py

was accidently removed in 130dfb08bf161314c0e5cb2753328ca1bde7617c

readding collector map

---

InventoryBuilder.py

get_vrops was only run once in the beginning. This led to not having all the targets when the actual targets are changing, e.g. new vRops instances are added

fix vrops target discovery

---

collectors/ClusterPropertiesCollector.py
collectors/ClusterStatsCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/VMPropertiesCollector.py
collectors/VMStatsCollector.py
tests/TestCollectors.py
tools/Resources.py
tools/helper.py

if more than 1000uuids are queried at the same time, all but first 1000 are dropped. This is mitigating it and introducing threading for fetching stats, otherwise this will increase runtime significantly

1000 uuids stats chunk

---

exporter.py

since the new uuid mechanism the scrapes are getting to long again. separating VM tasks here should achieve two things:
- consistent metrics, if VMs are taking too long
- federateable metrics for VMs too

VMs disabled by default #2

---

BaseCollector.py

Example error from `vrops-exporter-vrops-vc-b-0-host`
```
File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/usr/lib/python3.8/site-packages/prometheus_client/exposition.py", line 52, in prometheus_app
status, header, output = _bake_output(registry, accept_header, params)
File "/usr/lib/python3.8/site-packages/prometheus_client/exposition.py", line 40, in _bake_output
output = encoder(registry)
File "/usr/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
for metric in registry.collect():
File "/usr/lib/python3.8/site-packages/prometheus_client/registry.py", line 82, in collect
for metric in collector.collect():
File …
```

as long as the target is not in inventory

---

BaseCollector.py
collectors/ClusterPropertiesCollector.py
collectors/ClusterStatsCollector.py
collectors/DatastorePropertiesCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/VCenterPropertiesCollector.py
collectors/VCenterStatsCollector.py
collectors/VMPropertiesCollector.py
collectors/VMStatsCollector.py
exporter.py
inventory.py
tests/TestCollectors.py
tests/metrics.yaml
tools/Vrops.py

Generating an api status code metric to check, if the vrops target is reachable to make further API calls. 
example out:
```
vrops_api_response{class="datastorepropertiescollector",collector="vrops-vc-a-0-default",target="vrops-vc-a-0.cc.qa-de-1.cloud.sap"} 200.0
vrops_api_response{class="vcenterstatscollector",collector="vrops-vc-a-0-default",target="vrops-vc-a-0.cc.qa-de-1.cloud.sap"} 200.0
vrops_api_response{class="hostsystemstatscollector",collector="vrops-vc-a-0-host,target="vrops-vc-a-0.cc.qa-de-1.cloud.sap"} 200.0
```

added api response metric

---

tools/Vrops.py

objects need to be active objects, otherwise it could happen that vROps is fetching dated objects and then the exporter reports on these old dated metrics and objects too.

only fetch receiving objects

---

BaseCollector.py

in case of a complete reset it could lead to a waiting collector, even though the inventory has finished the run. It just wasn't ready at the time the collector was respawned

decrease retry for collectors

---

BaseCollector.py
collectors/PropertiesCollector.py
collectors/StatsCollector.py
collectors/VMPropertiesCollector.py
collectors/VMStatsCollector.py
tests/TestCollectors.py
tests/collector_config.yaml
tests/metrics.yaml
tools/Vrops.py

1. Increased request timeout in `get_latest_values_multiple()` to 60s
```
[2021-03-29 10:16:52,393] [ERROR] VMStatsMemoryCollector has problems getting latest data from: vrops-vc-a-0.cc.eu-de-1.cloud.sap - Error: HTTPSConnectionPool(host='vrops-vc-a-0.cc.eu-de-1.cloud.sap', port=443): Read timed out. (read timeout=30)
```
2. Introducing new metric called `vrops_api_response_time_seconds` for self monitoring purposes
3. Due to the slightly increased request processing to vrops, it can lead to a difference in resource ids in VMStatsCollector's `collect()`  and thus cause:
```python
File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File …
```

increase request timeout

---

tools/Vrops.py

Activated option that only current statistic values should be reported, i.e. the statistic values that have not published a value during the last collection cycles will be skipped. This option will be configurable in the future.

current values only

---

collectors/AlertCollector.py
requirements.txt

We have to install the `lxml` parser to use it. 
```python
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/vrops-exporter/InventoryBuilder.py", line 228, in query_vrops
self.alertdefinitions = Vrops.get_alertdefinitions(vrops, target, token)
File "/vrops-exporter/tools/Vrops.py", line 495, in get_alertdefinitions
recommendation_entry['description'] = remove_html_tags(rd.get("description"))
File "/vrops-exporter/tools/helper.py", line 20, in remove_html_tags
soup = BeautifulSoup(text, features="lxml")
File "/usr/lib/python3.9/site-packages/bs4/__init__.py", line 243, in __init__
raise FeatureNotFound( …
```

added lxml parser

---

tools/Vrops.py

We recently observed exporters not returning the scrape request after 60 seconds, missing timeouts are most likely the reason for it. Adding standard timeout of 60 seconds, please adjust if necessary.

Add timeout to all requests

---

collectors/CustomInfoMetricsGenerator.py
tests/collector_config.yaml

The present generator creates static vrops metrics from the collector configuration file. This is necessary because we had to set self-selected benchmarks, thresholds, etc. somewhere. In the initial case, we set a target version number that customers should minimally meet with their VMware vm tools. 
This will be a useful tool in the future to not force custom metrics into all vrops instances. 
The following example leads to this metric:
```ruby
vrops_virtualmachine_guest_tools_target_version_info{guest_tools_target_version="10.2.0", target="vrops-vc-a-0.cc.qa-de-1.cloud.sap"} 1.0
```

CustomInfoMetricsGenerator

---

collectors/SDDCAlertCollector.py
collectors/VcopsSelfMonitoringAlertCollector.py
collectors/VcopsSelfMonitoringPropertiesCollector.py
collectors/VcopsSelfMonitoringStatsCollector.py

Problems have occurred
```python 
AttributeError: 'VcopsSelfMonitoringPropertiesCollector' object has no attribute 'get_vcops_self_monitoring_objects_by_target'
File "/usr/lib/python3.9/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/usr/lib/python3.9/site-packages/prometheus_client/exposition.py", line 118, in prometheus_app
status, header, output = _bake_output(registry, accept_header, params)
File "/usr/lib/python3.9/site-packages/prometheus_client/exposition.py", line 100, in _bake_output
output = encoder(registry)
File "/usr/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
for metric in registry.collect():
File …
```

fixed func naming in vcops and sddc collectors

---

InventoryBuilder.py

Goal is to save some memory here.
3rd iteration stored is never actually used.
keeping 2 iterations tho for calls which are ongoing while the current iteration changes.

Dropping 1 iteration

---

BaseCollector.py
InventoryBuilder.py
collectors/AlertCollector.py

The alert definitions are a huge JSON blob that was retrieved and stored for each vrops instance and also for each alert collector. This consumed a lot of nonsensical memory.

Avoidance of multiple saving of alert definitions

---

InventoryBuilder.py
collectors/InventoryCollector.py
exporter.py
inventory.py
requirements.txt
tests/TestLaunchInventory.py

This PR fixes the issue where the inventory builder hangs when requesting vrops targets from atlas http sd endpoint. Error handling is now targeted at various problems that may occur and runs regardless of a successful request. Only the first run is terminated with code 0 because the `vrops_list` is not initially populated. In addition, a probe metric is supplied by the `InventoryCollector` to monitor the atlas http sd endpoint.

Atlas http endpoint error handling and probe metric added

---

tools/Vrops.py

The custom http code introduced crashes the dashboards and triggers a warning message as most are configured for codes over 500. The problem to be displayed is not really a problem as the resources may not be there and that is fine. We have set the code to 204, which means it is successful but does not contain any content.

Removed custom http code

---

collectors/DatastorePropertiesCollector.py
collectors/DatastoreStatsCollector.py

The label `storagepod` incorrectly shows `PoweredOff` because it is given as a static label, even if it is not a datastore from a storagepod. 
```
vrops_datastore_summary_datastore_accessible{
cluster="qa-de-1", 
cluster_type="controlplane", 
collector="vc-mgmt", 
datacenter="qa-de-1d", 
datastore="node00577", 
job="vrops-exporter", 
prometheus="vmware-monitoring/vmware", 
region="qa-de-1", 
storagepod="PoweredOff", 
type="NVMe", 
vcenter="vcenter"
}
```

fix storagepod labeling

---

BaseCollector.py
collectors/PropertiesCollector.py
collectors/StatsCollector.py

The collector should finish its collect()-run when receiving a SIGTERM. This is mainly used for a use case in kubernetes, where the given pod can be killed which would interrupt the current collect-run. Should be combined with terminationGracePeriodSeconds to avoid k8s waiting forever. A sane value would be something along 120 which is plenty of time to finish gracefully.
Fixes #245

catch sigterm in collect

---

BaseCollector.py
collectors/PropertiesCollector.py
collectors/StatsCollector.py
exporter.py

previous integration would only work if a single collector is registered. Multiple collectors would not be aware of the others being killed. Steering moved to exporter.py, as this is the only place where we are aware of the other instantiated collectors.

sigterm for multiple collectors

---

BaseCollector.py
collectors/InventoryCollector.py
inventory/Api.py
inventory/Builder.py
tools/Vrops.py

vrops API exposes the internal state of services on `suite-api/api/deployment/node/services/info`
```json
{
"service": [
{
"name": "ADMINUI",
"health": "OK",
"details": "Success, Service ADMINUI is running and responding",
"uptime": 5717296262,
"startedOn": 1673348078745
},
{
"name": "CASA",
"health": "OK",
"details": "Success, Service CASA is running and responding",
"uptime": 5717477120,
"startedOn": 1673347897944
},
{
"name": "COLLECTOR",
"health": "OK",
"details": "Success, Service COLLECTOR is running and responding",
"uptime": 5717286442,
"startedOn": 1673348088579
},
{
"name": "API",
"health": "OK",
"details": "Success, Service API is running and responding",
"uptime": 5717284954,
"startedOn": 1673348090088
},
{
"name": "LOCATOR",
"health": "OK",
"details": "Success, Service …
```

expose vrops node service states

---

tests/TestCollectors.py
tests/TestLaunchInventory.py
tests/inventory_launch.py

not yet everything, but in general working way better than before
In TestCollectors this is still failing but I haven't found the culprit yet, to overwrite the necessary call.
```
Problem connecting to vrops-vcenter-test.company.com - Error: HTTPSConnectionPool(host='vrops-vcenter-test.company.com', port=443): Max retries exceeded with url: /suite-api/api/deployment/node/services/info (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x40063f5f10>: Failed to resolve 'vrops-vcenter-test.company.com' ([Errno -2] Name does not resolve)"))
```

fixing testing
