sapcc/vrops-exporter

VropsCollector.py
module/SampleCollector.py
tools/get_modules.py
vrops-exporter.py

handle debug case if debug not set
ignore files starting with . on module load
removed obsolete query code
calling get_modules straight

minor tweaks

---

README.md
VropsCollector.py
tests/TestCollectors.py
tests/TestSampleCollector.py
tests/metrics.yaml
vrops_exporter.py

adding `tests` folder with module, which checks all collectors under `/module`. They need to have a section in `tests/metrics.yaml` and are being checked for all the metrics specified in there (also if there are more, less, different metrics).
Renamed main script to remove hyphen, or it couldn't be sourced. Also put all of the functionality in functions, so they can be called externally, like the test module does with `_run_prometheus_server()`
Gotta add some documentation, how tests are run.

Initial testing

---

exporter.py
tests/TestCollectors.py

unregistering collectors at the end
list param for collectors in run_prometheus_server for better testing
instantiating of collectors with name

preparing test for real two collector workload

---

InventoryBuilder.py

token fechting is now retried, if they can't be obtained

improved token handling

---

BaseCollector.py
InventoryBuilder.py
collectors/HostSystemCollector.py
tests/TestCollectors.py
tools/Resources.py

removed old flask entries for target and token
added target_tokens flask entry (gives a complete list now)
HostSystemCollector uses new method for fetching in parallel
key functionality is added in Resources

fetching statkey for multiple resources now

---

InventoryBuilder.py

if a vrops was not answering it was hanging forever, due to the retry
added a timeout and made vrops_query matching its name, it does just query a single vrops instance now. got to be instrumented from caller

fixing query_vrops stuck case

---

BaseCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/SampleCollector.py

adding describe function to avoid initial querying. gauges are now instantiated in init of collectors already.
removed code duplication for waiting stuff

describe methods and wait function

---

collectors/ClusterPropertiesCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/VMPropertiesCollector.py
exporter.py
tests/metrics.yaml

disable VMStatsCollector

---

collectors/ClusterStatsCollector.py
collectors/statkey.yaml
exporter.py
tests/TestCollectors.py
tests/metrics.yaml

ClusterStatsCollector has been created with metric "summary|number_running_hosts", this has been tested and getting proper number values of running hosts under the cluster
Request you please review and let me know if any changes needs to be done. -Thanks

ClusterStatsCollector

---

exporter.py
tests/metrics.yaml
tools/Resources.py

change order in register and for test

better error handling

---

collectors/VMPropertiesCollector.py
tools/Resources.py

skip vm_id in VMPropertiesCollector

catching JSONDecodeError

---

InventoryBuilder.py

inventories are only stored as iteration, when their run was successful

improving inventory versioning

---

BaseCollector.py

Kudos to @ThomasBuchinger for finding this one. 
It would now run every time it is getting queried, at least it won't stack up anymore. Suggestions welcome.

fixes #71 memory leaking

---

collectors/statkey.yaml
tests/metrics.yaml

added stat cpu_sockets_number

---

collectors/ClusterPropertiesCollector.py
collectors/ClusterStatsCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/VMPropertiesCollector.py
collectors/VMStatsCollector.py

this enables the collectors to fire all targets simultaneously. Big performance improvement :)

Thread collectors

---

collectors/VCenterPropertiesCollector.py
collectors/VCenterStatsCollector.py
collectors/property.yaml
collectors/statkey.yaml
exporter.py
tests/TestCollectors.py
tests/metrics.yaml

Added VCenterPropertiesCollector & Updated VCenterStatsCollector

---

collectors/VMStatsCollector.py
tools/Resources.py

moved to queue

---

README.md
collectors/statkey.yaml
tests/metrics.yaml

Tested with docker container setup.
Updated the readme to enter the container multiple times.

Added VCSA Certificate metric and updated readme

---

collectors/VCenterStatsCollector.py

bugfix single vc

---

InventoryBuilder.py
collectors/DatastorePropertiesCollector.py
collectors/DatastoreStatsCollector.py
resources/Datastore.py
tests/TestCollectors.py
tests/metrics.yaml

This gives us the possibility to filter the datastores by type.

added type for datastores

---

BaseCollector.py
collectors/ClusterPropertiesCollector.py
collectors/ClusterStatsCollector.py
collectors/DatastorePropertiesCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/VCenterPropertiesCollector.py
collectors/VCenterStatsCollector.py
collectors/VMPropertiesCollector.py
collectors/VMStatsCollector.py
exporter.py
tools/Vrops.py

worked on errors which occurred in production

keep exporter running

---

InventoryBuilder.py
inventory.py
tests/TestCollectors.py
tests/TestLaunchInventory.py

threading introduced for multiple runs to improve runtime.
shared timeout for threading
logging how long each target took to fetch its data

parallel calls for vrops targets

---

InventoryBuilder.py
resources/Cluster.py
resources/Datacenter.py
resources/Datastore.py
resources/Host.py
resources/Vcenter.py
resources/VirtualMachine.py
tests/TestCollectors.py
tools/Vrops.py

Reduce API calls to a minimum to keep the load on them as small as possible. At the same time, we need to update resources faster and more frequently so that dependent services work properly.

reduction of api calls and acceleration of the inventory building process

---

InventoryBuilder.py
collectors/InventoryCollector.py
inventory.py
tests/TestLaunchInventory.py

inventory items are not differentiated by label anymore, they've got a different name instead
fixed inventory launch and added testcase

multiple inventory item metrics and launchfix

---

collectors/InventoryCollector.py
collectors/PropertiesCollector.py
collectors/StatsCollector.py
tools/Vrops.py

1. Added `return` on `describe()` in InventoryCollector. The collector does not want to work otherwise.
2. The PropertiesCollector should be able to process the non-matching keys too.
3. Resource-uuids should never be empty, otherwise the requests are failing. Very rare, but happens.

final touches on collectors 2.0

---

BaseCollector.py

Whenever we restart the inventory, the collectors request iteration number 0, which does not exist. Now a wait for the initial iteration is implemented before each request of resources.
```Python
[2021-04-08 11:59:02,772] ERROR in app: Exception on /vrops-vc-d-0/vms/0 [GET]
File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File …
```

waiting for inital iteration per request

---

.github/workflows/coverage.yml
.github/workflows/pythonapp.yml
BaseCollector.py
InventoryBuilder.py
tools/Vrops.py

I have received feedback that virtual machines are missing. After a few tests I was able to confirm this and fix it. It looks like the amount of resource requests is limited to `10000`.

chunking vm requests

---

BaseCollector.py
collectors/AlertCollector.py
collectors/ClusterAlertCollector.py
collectors/ClusterPropertiesCollector.py
collectors/ClusterStatsCollector.py
collectors/DatastoreAlertCollector.py
collectors/DatastorePropertiesCollector.py
collectors/DatastoreStatsCollector.py
collectors/HostSystemAlertCollector.py
collectors/HostSystemPropertiesCollector.py
collectors/HostSystemStatsCollector.py
collectors/NSXTAdapterAlertCollector.py
collectors/NSXTMgmtClusterAlertCollector.py
collectors/NSXTMgmtClusterPropertiesCollector.py
collectors/NSXTMgmtClusterStatsCollector.py
collectors/NSXTMgmtNodeAlertCollector.py
collectors/NSXTMgmtNodePropertiesCollector.py
collectors/NSXTMgmtNodeStatsCollector.py
collectors/NSXTMgmtServiceAlertCollector.py
collectors/VCenterAlertCollector.py
collectors/VCenterPropertiesCollector.py
collectors/VCenterStatsCollector.py
tools/Vrops.py

- Description of alerts added
- Secured the setting of labels
- Without alert definitions the `AlertCollector` does not run
- Removed the access to the protected attribute `_labelnames`
- Using the info metrics family to set alert labels dynamically

Fixing errors and solving inconsistent labels

---

InventoryBuilder.py

See commit message for further insights

inventoryBuilder memory leak fix

---

tools/Vrops.py

This is a hotfix to monitor grey VMs a soon as possible. This is going to be configurable in the future.

[vrops-exporter] collecting grey vms

---

BaseCollector.py
InventoryBuilder.py
collectors/InventoryCollector.py
collectors/SDDCAlertCollector.py
collectors/VcopsSelfMonitoringAlertCollector.py
collectors/VcopsSelfMonitoringPropertiesCollector.py
collectors/VcopsSelfMonitoringStatsCollector.py
tests/inventory_config.yaml
tools/Vrops.py

better naming for sddc and vcops objects
decrease overhead for InventoryCollector

consider changes in the inventory config

---

InventoryBuilder.py

Prevent dicts from being emptied

using defaultdicts

---

.github/workflows/pythonapp.yml
InventoryBuilder.py
README.md
inventory.py
requirements.txt
tests/TestCollectors.py
tests/inventory_config.yaml

inventory_config for target configuration

---

BaseCollector.py
InventoryBuilder.py
collectors/SDRSStatsCollector.py
tests/TestCollectors.py
tests/collector_config.yaml
tests/inventory_config.yaml
tests/metrics.yaml
tools/Vrops.py

Updated code to read SDRS Cluster Capacity Percentage from the API.

++SDRS Cluster Capacity

---

InventoryBuilder.py

skip vcops adapter if not present

---

.github/workflows/coverage.yml
.github/workflows/pythonapp.yml

At least it fixes linting, even if testing is still broken.

bump workflows

---

tools/Vrops.py

added nfs datastore type to the datastore metrics so it can be filtered in prometheus queries

added nfs datastore type
